export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USES_GOOGLE: 'AUTH_USES_GOOGLE',
  AUTH_NO_PASSWORD_SET: 'AUTH_NO_PASSWORD_SET',
  AUTH_CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',
  AUTH_MISSING_CODE: 'AUTH_MISSING_CODE',
  AUTH_GOOGLE_NO_ID_TOKEN: 'AUTH_GOOGLE_NO_ID_TOKEN',
  AUTH_GOOGLE_EMPTY_PAYLOAD: 'AUTH_GOOGLE_EMPTY_PAYLOAD',
  AUTH_GOOGLE_MISSING_FIELDS: 'AUTH_GOOGLE_MISSING_FIELDS',

  USERNAME_TAKEN: 'USERNAME_TAKEN',

  NOT_A_CREATOR: 'NOT_A_CREATOR',
  CREATOR_NOT_FOUND: 'CREATOR_NOT_FOUND',
  CREATOR_PRICE_INVALID: 'CREATOR_PRICE_INVALID',
  CREATOR_PRICE_STEP: 'CREATOR_PRICE_STEP',
  CREATOR_PRICE_MAX: 'CREATOR_PRICE_MAX',

  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_SELF_SEND: 'MESSAGE_SELF_SEND',
  MESSAGE_PRICE_TOO_LOW: 'MESSAGE_PRICE_TOO_LOW',
  MESSAGE_MARK_READ_FORBIDDEN: 'MESSAGE_MARK_READ_FORBIDDEN',
  MESSAGE_PAY_FORBIDDEN: 'MESSAGE_PAY_FORBIDDEN',
  MESSAGE_ALREADY_PAID: 'MESSAGE_ALREADY_PAID',
  MESSAGE_ACCESS_DENIED: 'MESSAGE_ACCESS_DENIED',
  MESSAGE_DELETE_FORBIDDEN: 'MESSAGE_DELETE_FORBIDDEN',
  MESSAGE_EDIT_PRICE_FORBIDDEN: 'MESSAGE_EDIT_PRICE_FORBIDDEN',

  SOCIAL_LINKS_CREATOR_ONLY: 'SOCIAL_LINKS_CREATOR_ONLY',
  SOCIAL_LINK_INVALID_URL: 'SOCIAL_LINK_INVALID_URL',
  SOCIAL_LINK_PLATFORM_INVALID: 'SOCIAL_LINK_PLATFORM_INVALID',
  SOCIAL_LINK_DOMAIN_MISMATCH: 'SOCIAL_LINK_DOMAIN_MISMATCH',

  VALIDATION_CODE_REQUIRED: 'VALIDATION_CODE_REQUIRED',
  VALIDATION_EMAIL_INVALID: 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PASSWORD_REQUIRED: 'VALIDATION_PASSWORD_REQUIRED',
  VALIDATION_PASSWORD_MIN: 'VALIDATION_PASSWORD_MIN',
  VALIDATION_PASSWORD_UPPERCASE: 'VALIDATION_PASSWORD_UPPERCASE',
  VALIDATION_PASSWORD_NUMBER: 'VALIDATION_PASSWORD_NUMBER',
  VALIDATION_CURRENT_PASSWORD_REQUIRED: 'VALIDATION_CURRENT_PASSWORD_REQUIRED',

  VALIDATION_DISPLAY_NAME_MIN: 'VALIDATION_DISPLAY_NAME_MIN',
  VALIDATION_DISPLAY_NAME_MAX: 'VALIDATION_DISPLAY_NAME_MAX',
  VALIDATION_USERNAME_MIN: 'VALIDATION_USERNAME_MIN',
  VALIDATION_USERNAME_MAX: 'VALIDATION_USERNAME_MAX',
  VALIDATION_USERNAME_FORMAT: 'VALIDATION_USERNAME_FORMAT',
  VALIDATION_PROFILE_AT_LEAST_ONE_FIELD: 'VALIDATION_PROFILE_AT_LEAST_ONE_FIELD',

  VALIDATION_URL_INVALID: 'VALIDATION_URL_INVALID',
  VALIDATION_URL_TOO_LONG: 'VALIDATION_URL_TOO_LONG',

  VALIDATION_CREATOR_ID_INVALID: 'VALIDATION_CREATOR_ID_INVALID',
  VALIDATION_TITLE_REQUIRED: 'VALIDATION_TITLE_REQUIRED',
  VALIDATION_TITLE_MAX: 'VALIDATION_TITLE_MAX',
  VALIDATION_MESSAGE_REQUIRED: 'VALIDATION_MESSAGE_REQUIRED',
  VALIDATION_MESSAGE_MAX: 'VALIDATION_MESSAGE_MAX',
  VALIDATION_PRICE_INTEGER: 'VALIDATION_PRICE_INTEGER',
  VALIDATION_PRICE_MIN: 'VALIDATION_PRICE_MIN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
